[project]
name = "ColorRandomizer"
version = "1.0.11"
authors = [{ name = "galqawala" }]
description = "Randomizes your character's colors and head, and every vehicle's paint, on spawn - plus a keybind to reroll on demand."

[tool.sdkmod]
name = "ColorRandomizer"
supported_games = ["BL1", "BL1E"]
coop_support = "Unknown"
auto_enable = true
download = "https://github.com/galqawala/ColorRandomizer/raw/refs/heads/master/ColorRandomizer.sdkmod"

[tool.sdkmod.license]
name = "GPL3"
url = "https://choosealicense.com/licenses/gpl-3.0/"
